export interface Product {
    id?: number;          // Optional, because it will be generated by the backend
    name: string;
    description: string;
    price: number;
    imagedata: string;    // Optional, to hold the image URL or base64 string
  }
  